### ISSUE TITLE
As a user, I want to be able to answer a question

### ISSUE THREAD

**Issue by shadijiha** [usamasaleem1/StaccOverflow#48]
The System shall allow the user to add a comment on a question
The System shall allow the user to upvote comments

Points: 5
Priority:  **Medium**
Risk:  **High Risk, High value**
Estimated time:  **4h**

**Comment by uzairali245** [comment]
**Acceptance Testing**
-Once a user is signed in he can click on title of any of questions on home page
-User will be redirected to answer page of the following question
-User can answer the following question by writing potential solution in text box
- Click submit once you're done and your answer will be posted on answer page of the selected question
